name: Lint

on:
  push:
  pull_request:

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install lint tools
        run: |
          pip install black==25.11.0 flake8

      - name: Run formatter
        run: black --check .

      - name: Run flake8
        run: flake8 .
